### ISSUE TITLE
ERROR on proc 0: Cannot open MEAM potential file CH_library.meam

### ISSUE THREAD

**Issue by xdlzuups** [WSUChem537/Homeworks#3]
Hello Dr. Clark,

I got an error message when running LAMMPS with isobutane. It as below:

# --------------- Define Interatomic Potential -------------------
pair_style meam
pair_coeff * * CH_library.meam C H CH.meam C H
ERROR on proc 0: Cannot open MEAM potential file CH_library.meam (../pair_meamc.cpp:332)
Last command: pair_coeff * * CH_library.meam C H CH.meam C H

I searched the library and was intending to put the library into the same directory with the calclation. But I could not find the library in lammps downloading package or in their website. Please let me how I can solve this problem. Thank you very much.

**Comment by WSUChem537** [comment]
got this fixed a while ago, just closing issue now
